CREATE TABLE IF NOT EXISTS regular_order_entity
(
    id             BIGINT PRIMARY KEY generated by default as identity,
    order_id       BIGINT       NOT NULL,
    currency_chain VARCHAR(255) NOT NULL,
    operation      VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    quantity       NUMERIC      NOT NULL,
    price          NUMERIC      NOT NULL
);